In [1]:
from typing import Dict

# ==============================================================================
# Task 2: Combinatorial DP - Climbing a Staircase
# ==============================================================================

# ------------------------------------------------------------------------------
# Part 1: Recursive Solution
# ------------------------------------------------------------------------------
# This is the pure recursive solution. It's the most direct translation of the
# problem's logic but is very inefficient for larger numbers.

def climb_recursive(n: int) -> int:
    if n == 0:
        return 1
    if n < 0:
        return 0
    return climb_recursive(n - 1) + climb_recursive(n - 2) + climb_recursive(n - 3)

# ------------------------------------------------------------------------------
# Part 2: Top-Down Dynamic Programming (Memoization)
# ------------------------------------------------------------------------------
# This is the top-down dynamic programming solution using memoization. It uses a
# cache (a dictionary named `memo`) to store the results of subproblems.

def climb_top_down(n: int) -> int:
    memo: Dict[int, int] = {}
    def solve(current_step: int) -> int:
        if current_step == 0:
            return 1
        if current_step < 0:
            return 0
        if current_step in memo:
            return memo[current_step]
        result = solve(current_step - 1) + solve(current_step - 2) + solve(current_step - 3)
        memo[current_step] = result
        return result
    return solve(n)

# ------------------------------------------------------------------------------
# Part 3: Bottom-Up Dynamic Programming (Tabulation)
# ------------------------------------------------------------------------------
# This is the bottom-up dynamic programming solution using tabulation. It solves
# the problem iteratively by building up a table of solutions.

def climb_bottom_up(n: int) -> int:
    if n == 0:
        return 1
    dp = [0] * (n + 1)
    dp[0] = 1
    for i in range(1, n + 1):
        ways = 0
        if i - 1 >= 0:
            ways += dp[i - 1]
        if i - 2 >= 0:
            ways += dp[i - 2]
        if i - 3 >= 0:
            ways += dp[i - 3]
        dp[i] = ways
    return dp[n]

# ==============================================================================
# Demonstration
# ==============================================================================
# This final section demonstrates how to run the functions and verifies that
# they all produce the same correct result for a given input.

if __name__ == '__main__':
    num_steps = 25
    print(f"Calculating distinct ways to climb {num_steps} steps:\n")

    print("--- Top-Down DP (Memoization) ---")
    ways_memo = climb_top_down(num_steps)
    print(f"Result: {ways_memo}\n")

    print("--- Bottom-Up DP (Tabulation) ---")
    ways_tab = climb_bottom_up(num_steps)
    print(f"Result: {ways_tab}\n")

    print("--- Pure Recursive Solution ---")
    small_n = 15
    ways_rec = climb_recursive(small_n)
    print(f"Result (for n={small_n}): {ways_rec}\n")

    print(f"--- Verification for n=10 ---")
    print(f"Recursive:    {climb_recursive(10)}")
    print(f"Top-Down DP:  {climb_top_down(10)}")
    print(f"Bottom-Up DP: {climb_bottom_up(10)}")

Calculating distinct ways to climb 25 steps:

--- Top-Down DP (Memoization) ---
Result: 2555757

--- Bottom-Up DP (Tabulation) ---
Result: 2555757

--- Pure Recursive Solution ---
Result (for n=15): 5768

--- Verification for n=10 ---
Recursive:    274
Top-Down DP:  274
Bottom-Up DP: 274


In [2]:
import numpy as np # Using numpy for easier matrix creation and printing

def lcs_dynamic_programming(seq1: str, seq2: str):
    """
    Finds the Longest Common Subsequence (LCS) of two sequences using
    a classic dynamic programming approach.

    Args:
        seq1: The first string sequence.
        seq2: The second string sequence.

    Returns:
        A tuple containing:
        - The completed DP matrix (as a numpy array).
        - The Longest Common Subsequence (as a string).
    """
    m = len(seq1)
    n = len(seq2)

    # 1. Compute the LCS matrix C
    # Initialize the DP table (matrix C) with zeros.
    # The dimensions are (m+1) x (n+1) to handle base cases.
    dp_matrix = np.zeros((m + 1, n + 1), dtype=int)

    # Fill the matrix based on the LCS recurrence relation
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            if seq1[i - 1] == seq2[j - 1]:
                # If characters match, take the diagonal value and add 1
                dp_matrix[i][j] = 1 + dp_matrix[i - 1][j - 1]
            else:
                # If they don't match, take the max of the top or left value
                dp_matrix[i][j] = max(dp_matrix[i - 1][j], dp_matrix[i][j - 1])

    # 2. Reconstruct the actual LCS string by backtracking from the bottom-right corner
    lcs = []
    i, j = m, n
    while i > 0 and j > 0:
        # If characters match, this character is part of the LCS
        if seq1[i - 1] == seq2[j - 1]:
            lcs.append(seq1[i - 1])
            i -= 1 # Move diagonally up-left
            j -= 1
        # If not, move in the direction of the larger value in the matrix
        elif dp_matrix[i - 1][j] > dp_matrix[i][j - 1]:
            i -= 1 # Move up
        else:
            j -= 1 # Move left

    # The LCS is built backwards, so we reverse it to get the correct order
    return dp_matrix, "".join(reversed(lcs))


def print_lcs_results(seq1, seq2):
    """A helper function to run and print the LCS results nicely."""
    print(f"Sequence 1: '{seq1}'")
    print(f"Sequence 2: '{seq2}'")
    
    dp_matrix, lcs = lcs_dynamic_programming(seq1, seq2)
    
    print("\nLCS DP Matrix (C):")
    print(dp_matrix)
    
    print(f"\nLength of LCS: {len(lcs)}")
    print(f"LCS Content: '{lcs}'")
    print("-" * 40)


# ==============================================================================
# 3. Test the implementation on several string pairs
# ==============================================================================

if __name__ == '__main__':
    # Define test cases, including edge cases
    test_cases = [
        # Standard case
        ("AGGTAB", "GXTXAYB"),

        ("ABCDE", ""),

        ("PYTHON", "JAVA"),

        ("stone", "longest"),

        ("AAAA", "BABA"),

        ("ABCDGH", "AEDFHR"),
    ]

    # Run and print results for each test case
    for s1, s2 in test_cases:
        print_lcs_results(s1, s2)

Sequence 1: 'AGGTAB'
Sequence 2: 'GXTXAYB'

LCS DP Matrix (C):
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1]
 [0 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1]
 [0 1 1 2 2 2 2 2]
 [0 1 1 2 2 3 3 3]
 [0 1 1 2 2 3 3 4]]

Length of LCS: 4
LCS Content: 'GTAB'
----------------------------------------
Sequence 1: 'ABCDE'
Sequence 2: ''

LCS DP Matrix (C):
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]]

Length of LCS: 0
LCS Content: ''
----------------------------------------
Sequence 1: 'PYTHON'
Sequence 2: 'JAVA'

LCS DP Matrix (C):
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Length of LCS: 0
LCS Content: ''
----------------------------------------
Sequence 1: 'stone'
Sequence 2: 'longest'

LCS DP Matrix (C):
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 1 2]
 [0 0 1 1 1 1 1 2]
 [0 0 1 2 2 2 2 2]
 [0 0 1 2 2 3 3 3]]

Length of LCS: 3
LCS Content: 'one'
----------------------------------------
Sequence 1: 'AAAA'
Sequence 2: 'BABA'

LCS DP Matrix (C):
[[0 0 0 0 0]
 [0 0 1 1 

In [3]:
import time
import random

def knapsack_01(items, capacity):
    """
    Solves the 0/1 knapsack problem using dynamic programming.

    Args:
        items (list): A list of tuples, where each tuple represents an item
                      in the format (weight, value).
        capacity (int): The maximum weight capacity of the knapsack.

    Returns:
        int: The maximum total value of items that can be included in the knapsack.
    """
    # Create a DP table to store the maximum value for each capacity.
    # dp[w] will store the maximum value that can be achieved with a knapsack of capacity w.
    dp = [0] * (capacity + 1)

    # Iterate through each item in the list
    for weight, value in items:
        # =================== KEY CHANGE FROM UNBOUNDED KNAPSACK ===================
        # For the 0/1 knapsack problem, we must iterate backwards through the capacities.
        # This is the crucial difference from the unbounded knapsack problem, which
        # iterates forwards (e.g., for w in range(weight, capacity + 1):).
        #
        # Why iterate backwards?
        # By iterating from `capacity` down to `weight`, we ensure that for any given item,
        # we use it at most ONCE per capacity calculation. When we calculate `dp[w]`,
        # the value of `dp[w - weight]` is from the PREVIOUS iteration (i.e., before
        # considering the current item).
        #
        # If we were to iterate forwards, `dp[w - weight]` would have already been updated
        # in the current loop, potentially including the current item multiple times,
        # which would solve the unbounded knapsack problem instead.
        # ========================================================================
        for w in range(capacity, weight - 1, -1):
            # Decide whether to include the current item or not.
            # We take the maximum of:
            # 1. dp[w] (not including the current item)
            # 2. dp[w - weight] + value (including the current item)
            dp[w] = max(dp[w], dp[w - weight] + value)

    # The last element of the dp table contains the maximum value for the given capacity
    return dp[capacity]

# --- Main execution block ---
if __name__ == "__main__":
    
    # --- Test 1: A basic example with a known solution ---
    print("--- Basic Example ---")
    basic_capacity = 50
    basic_items = [(10, 60), (20, 100), (30, 120)]
    
    # The optimal solution is to choose items with weights 20 and 30,
    # giving a total weight of 50 and a total value of 100 + 120 = 220.
    
    print(f"Capacity: {basic_capacity}")
    print(f"Items (weight, value): {basic_items}")
    
    max_value_basic = knapsack_01(basic_items, basic_capacity)
    
    print(f"\nMaximum value: {max_value_basic}")
    print("Expected value: 220")
    print("-" * 25)

    # --- Test 2: A large input case to evaluate performance ---
    print("\n--- Large Input Case ---")
    large_capacity = 10000
    num_items = 500
    
    # Generate a large list of random items
    large_items = [(random.randint(1, 100), random.randint(1, 500)) for _ in range(num_items)]
    
    print(f"Capacity: {large_capacity}")
    print(f"Number of items: {num_items}")

    start_time = time.time()
    max_value_large = knapsack_01(large_items, large_capacity)
    end_time = time.time()
    
    execution_time = end_time - start_time
    
    print(f"\nMaximum value: {max_value_large}")
    print(f"Execution time: {execution_time:.4f} seconds")
    print("-" * 25)

--- Basic Example ---
Capacity: 50
Items (weight, value): [(10, 60), (20, 100), (30, 120)]

Maximum value: 220
Expected value: 220
-------------------------

--- Large Input Case ---
Capacity: 10000
Number of items: 500

Maximum value: 90264
Execution time: 0.5225 seconds
-------------------------


In [4]:
from typing import List

# ===================================================================
#  Solution 1: Top-Down with Memoization (Recursive)
# ===================================================================

def coin_change_memoization(coins: List[int], amount: int) -> int:
    """
    Finds the minimum number of coins to make a given amount using a 
    top-down recursive approach with memoization.

    Args:
        coins (List[int]): A list of available coin denominations.
        amount (int): The target amount to make.

    Returns:
        int: The minimum number of coins required, or -1 if impossible.
    """
    memo = {}

    def solve(rem_amount):
        if rem_amount == 0:
            return 0
        if rem_amount < 0:
            return float('inf')
        if rem_amount in memo:
            return memo[rem_amount]

        min_coins = float('inf')
        
        for coin in coins:
            result = solve(rem_amount - coin)
            if result != float('inf'):
                min_coins = min(min_coins, result + 1)
        
        memo[rem_amount] = min_coins
        return min_coins

    final_result = solve(amount)
    
    return -1 if final_result == float('inf') else int(final_result)


# ===================================================================
#  Solution 2: Bottom-Up with Tabulation (Iterative)
# ===================================================================

def coin_change_tabulation(coins: List[int], amount: int) -> int:
    """
    Finds the minimum number of coins to make a given amount using a 
    bottom-up iterative approach (tabulation).

    Args:
        coins (List[int]): A list of available coin denominations.
        amount (int): The target amount to make.

    Returns:
        int: The minimum number of coins required, or -1 if impossible.
    """
    dp = [amount + 1] * (amount + 1)
    dp[0] = 0
    
    for a in range(1, amount + 1):
        for coin in coins:
            if a - coin >= 0:
                dp[a] = min(dp[a], 1 + dp[a - coin])
                
    if dp[amount] > amount:
        return -1
    else:
        return dp[amount]

# --- Main execution block for testing ---
if __name__ == "__main__":
    
    # Test Case 1 (from example)
    print("--- Test Case 1 ---")
    coins1 = [1, 2, 5]
    amount1 = 11
    print(f"Coins: {coins1}, Amount: {amount1}")
    print(f"Memoization Solution: {coin_change_memoization(coins1, amount1)}")
    print(f"Tabulation Solution:  {coin_change_tabulation(coins1, amount1)}")
    print("Expected: 3\n")

    # Test Case 2 (from example - impossible case)
    print("--- Test Case 2 ---")
    coins2 = [2]
    amount2 = 3
    print(f"Coins: {coins2}, Amount: {amount2}")
    print(f"Memoization Solution: {coin_change_memoization(coins2, amount2)}")
    print(f"Tabulation Solution:  {coin_change_tabulation(coins2, amount2)}")
    print("Expected: -1\n")

    # Test Case 3 (greedy approach fails here)
    print("--- Test Case 3 ---")
    coins3 = [1, 3, 4]
    amount3 = 6
    print(f"Coins: {coins3}, Amount: {amount3}")
    print(f"Memoization Solution: {coin_change_memoization(coins3, amount3)}")
    print(f"Tabulation Solution:  {coin_change_tabulation(coins3, amount3)}")
    print("Expected: 2\n")

    # Test Case 4 (empty coins list)
    print("--- Test Case 4 ---")
    coins4 = []
    amount4 = 5
    print(f"Coins: {coins4}, Amount: {amount4}")
    print(f"Memoization Solution: {coin_change_memoization(coins4, amount4)}")
    print(f"Tabulation Solution:  {coin_change_tabulation(coins4, amount4)}")
    print("Expected: -1\n")

--- Test Case 1 ---
Coins: [1, 2, 5], Amount: 11
Memoization Solution: 3
Tabulation Solution:  3
Expected: 3

--- Test Case 2 ---
Coins: [2], Amount: 3
Memoization Solution: -1
Tabulation Solution:  -1
Expected: -1

--- Test Case 3 ---
Coins: [1, 3, 4], Amount: 6
Memoization Solution: 2
Tabulation Solution:  2
Expected: 2

--- Test Case 4 ---
Coins: [], Amount: 5
Memoization Solution: -1
Tabulation Solution:  -1
Expected: -1

